### ISSUE TITLE
entrypoint not found

### ISSUE THREAD

**Issue by MAmmerlaan** [wichers/thermostart#12]
Trying to get the container working, to unbrick my TS. :)

Seps to reproduce
- Git pull
- Update .env.dev (only SECRET_KEY param)
- (from root directory)
- docker-compose build
- docker-compose up -d

Container fails to start and exits with the following error 'exec /usr/src/app/entrypoint.sh: no such file or directory'
So cant do the chmod +x on the entrypoint file 

I am trying to run this on a W11 machine with docker desktop.

**Comment by wichers** [comment]
There have been quite some changes after yesterday's commit. Please checkout the latest version. Although I haven't had this error, to be certain I've also done a chmod +x in git, which should flag it on checkout. 

Could you try again with the latest version?

**Comment by MAmmerlaan** [comment]
I have pulled in recent changes, but no change. 
Removed all container (in docker desktop), rebuilt, restarted, but the container fails instantly.

I applied this fix, and that worked :).
https://stackoverflow.com/questions/44460825/entrypoint-file-not-found

Apparently an encoding issue on git on windows.

**Comment by wichers** [comment]
Well done! Out of 10 proposed stackoverflow fixes, which one did you apply?

**Comment by wichers** [comment]
ah, probably CRLF

**Comment by MAmmerlaan** [comment]
I have applied the first advise. 
`I had this problem with Docker for Windows and the solution was changing the entrypoint script file from CRLF -> LF.`
But haven't found a way to elegantly push that to version control. Since most solutions seems to be around local git config.

**Comment by MAmmerlaan** [comment]
You can go ahead and archive this issue.
There is no real solution (other then adjust the CRLF property).
Since it only plays up on Windows, when building the container, and since it cannot be checked in. A true resolvement is hard.

Just leave it here as future reference should be sufficient imho.
