### ISSUE TITLE
Running dockerfile on arm requires a specific netcat

### ISSUE THREAD

**Issue by jvo85** [wichers/thermostart#4]
I had the choice between:
netcat-openbsd/stable,stable 1.219-1 armel
netcat-traditional/stable,stable 1.10-47 armel

I am using the first one atm, assuming the extended functionality is required.

Can we make this install specific to one of these packages, assuming this will also work on originally used architecture?

**Comment by wichers** [comment]
moved from postgresql to sqlite3, netcat dependency (checking is postgresql is up) has been removed
