### ISSUE TITLE
Mobile: Overview page difficult to use due to frequent navigation to the Schedule page.

### ISSUE THREAD

**Issue by jvo85** [wichers/thermostart#5]
Mobile Safari and Opera seem to render the site in such a way that it is very easy to trigger the onclick in the overview page, thereby going to the exceptions (Agenda) page.

Only Firefox (android) seems to handle it better.

The ithermostat.js contains this onclick handling, disabling it allows normal use of the webpage, one can still navigate to the schedule page using the top menu:
    _// GOTO exceptions agenda if the overview contains is clicked. Dirty but functional ;-)
    $('.overview-container').on('click touchstart', function() {
        app.navigate('exceptions', { trigger: true });
    });_

**Comment by wichers** [comment]
fixed by UI improvement wrt Mobile usage
