### ISSUE TITLE
Overview time indicator is misaligned

### ISSUE THREAD

**Issue by jvo85** [wichers/thermostart#7]
As can be seen on the picture, the time indicator shows the right time in the wrong place:
![image](https://github.com/wichers/thermostart/assets/162290380/bd9b294d-9f7a-4f1c-ad8c-2f8b0899f38f)

Overview.js contains some calculation (line 260) which appears to not align completely to the screen itself at different times of the day:
_var gridCoordinates = { x: now.isoWeekday() - 1, y: now.hours() * ts.OVERVIEW_RESOLUTION };_

**Comment by wichers** [comment]
This has been fixed by your "UI improvement wrt Mobile usage" commit, correct?
