### ISSUE TITLE
Data does not persist between docker-compose down and up

### ISSUE THREAD

**Issue by jvo85** [wichers/thermostart#9]
Every time I perform an down and up version, with or without doing an build in between, I need to reregister my Account.

The Docker volumes are still there (docker volume ls), and both volumes keep the same ID between restart, but somehow the account info and schedule do not persist (on my machine).

Repro:
GIVEN The docker image is running with a working account and schedule.
WHEN docker-compose -f docker-compose.prod.yml down
AND docker-compose -f docker-compose.prod.yml up -d
AND Login
THEN Account is not recognized

**Comment by wichers** [comment]
it does persist, but make sure there is no FLASK_DEBUG=1 in your prod env file

**Comment by jvo85** [comment]
Yes, that was it!

Maybe an idea to expand the readme to include what the effect is of enabling Flask debugging?
